// <auto-generated />
using System;
using MagicVilla_VillaApi.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_VillaApi.Migrations
{
    [DbContext(typeof(VillaDbContext))]
    [Migration("20240930235411_VillaNumber")]
    partial class VillaNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_VillaApi.Model.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Swimming pool, jacuzzi, gym",
                            CreatedAt = new DateTime(2024, 10, 1, 2, 54, 9, 619, DateTimeKind.Local).AddTicks(2702),
                            Details = "This is a beautiful villa with 1 bedroom and 1 bathroom.",
                            ImageUrl = "villa1.jpg",
                            Name = "Villa 1",
                            Occupancy = 5,
                            Rate = 101.0,
                            Sqft = 2001,
                            UpdatedAt = new DateTime(2024, 10, 1, 2, 54, 9, 619, DateTimeKind.Local).AddTicks(2704)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Swimming pool, jacuzzi, gym",
                            CreatedAt = new DateTime(2024, 10, 1, 2, 54, 9, 619, DateTimeKind.Local).AddTicks(2707),
                            Details = "This is a beautiful villa with 2 bedrooms and 2 bathrooms.",
                            ImageUrl = "villa2.jpg",
                            Name = "Villa 2",
                            Occupancy = 6,
                            Rate = 102.0,
                            Sqft = 2002,
                            UpdatedAt = new DateTime(2024, 10, 1, 2, 54, 9, 619, DateTimeKind.Local).AddTicks(2709)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Swimming pool, jacuzzi, gym",
                            CreatedAt = new DateTime(2024, 10, 1, 2, 54, 9, 619, DateTimeKind.Local).AddTicks(2711),
                            Details = "This is a beautiful villa with 3 bedrooms and 3 bathrooms.",
                            ImageUrl = "villa3.jpg",
                            Name = "Villa 3",
                            Occupancy = 7,
                            Rate = 103.0,
                            Sqft = 2003,
                            UpdatedAt = new DateTime(2024, 10, 1, 2, 54, 9, 619, DateTimeKind.Local).AddTicks(2712)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "Swimming pool, jacuzzi, gym",
                            CreatedAt = new DateTime(2024, 10, 1, 2, 54, 9, 619, DateTimeKind.Local).AddTicks(2715),
                            Details = "This is a beautiful villa with 4 bedrooms and 4 bathrooms.",
                            ImageUrl = "villa4.jpg",
                            Name = "Villa 4",
                            Occupancy = 8,
                            Rate = 104.0,
                            Sqft = 2004,
                            UpdatedAt = new DateTime(2024, 10, 1, 2, 54, 9, 619, DateTimeKind.Local).AddTicks(2716)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "Swimming pool, jacuzzi, gym",
                            CreatedAt = new DateTime(2024, 10, 1, 2, 54, 9, 619, DateTimeKind.Local).AddTicks(2718),
                            Details = "This is a beautiful villa with 5 bedrooms and 5 bathrooms.",
                            ImageUrl = "villa5.jpg",
                            Name = "Villa 5",
                            Occupancy = 9,
                            Rate = 105.0,
                            Sqft = 2005,
                            UpdatedAt = new DateTime(2024, 10, 1, 2, 54, 9, 619, DateTimeKind.Local).AddTicks(2719)
                        });
                });

            modelBuilder.Entity("MagicVilla_VillaApi.Model.VillaNumber", b =>
                {
                    b.Property<int>("VillaNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("VillaNo");

                    b.ToTable("villaNumbers");

                    b.HasData(
                        new
                        {
                            VillaNo = 102,
                            CreatedAt = new DateTime(2024, 10, 1, 2, 54, 9, 619, DateTimeKind.Local).AddTicks(2522),
                            SpecialDetails = "Test",
                            UpdatedAt = new DateTime(2024, 10, 1, 2, 54, 9, 619, DateTimeKind.Local).AddTicks(2588)
                        },
                        new
                        {
                            VillaNo = 103,
                            CreatedAt = new DateTime(2024, 10, 1, 2, 54, 9, 619, DateTimeKind.Local).AddTicks(2590),
                            SpecialDetails = "Test",
                            UpdatedAt = new DateTime(2024, 10, 1, 2, 54, 9, 619, DateTimeKind.Local).AddTicks(2592)
                        },
                        new
                        {
                            VillaNo = 303,
                            CreatedAt = new DateTime(2024, 10, 1, 2, 54, 9, 619, DateTimeKind.Local).AddTicks(2593),
                            SpecialDetails = "Test",
                            UpdatedAt = new DateTime(2024, 10, 1, 2, 54, 9, 619, DateTimeKind.Local).AddTicks(2595)
                        },
                        new
                        {
                            VillaNo = 202,
                            CreatedAt = new DateTime(2024, 10, 1, 2, 54, 9, 619, DateTimeKind.Local).AddTicks(2596),
                            SpecialDetails = "Test",
                            UpdatedAt = new DateTime(2024, 10, 1, 2, 54, 9, 619, DateTimeKind.Local).AddTicks(2598)
                        },
                        new
                        {
                            VillaNo = 508,
                            CreatedAt = new DateTime(2024, 10, 1, 2, 54, 9, 619, DateTimeKind.Local).AddTicks(2600),
                            SpecialDetails = "Test",
                            UpdatedAt = new DateTime(2024, 10, 1, 2, 54, 9, 619, DateTimeKind.Local).AddTicks(2601)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
